// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3DWSoZURSDiUF-x5ASyXK4Axp1oE_V5k',
    appId: '1:565444919181:web:62ce32cf75eddc382487c4',
    messagingSenderId: '565444919181',
    projectId: 'dungeon-21925',
    authDomain: 'dungeon-21925.firebaseapp.com',
    storageBucket: 'dungeon-21925.firebasestorage.app',
    measurementId: 'G-B45R751J0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXFXRFBjMzIJXh0ZiZeAdi4KrU8rLQ8w',
    appId: '1:565444919181:android:bfc39882b87c80fa2487c4',
    messagingSenderId: '565444919181',
    projectId: 'dungeon-21925',
    storageBucket: 'dungeon-21925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDspKVZndLPYj7RxtjnwM12buuKsoOyKZE',
    appId: '1:565444919181:ios:ab4d357217e672ea2487c4',
    messagingSenderId: '565444919181',
    projectId: 'dungeon-21925',
    storageBucket: 'dungeon-21925.firebasestorage.app',
    iosBundleId: 'com.example.dungeon2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDspKVZndLPYj7RxtjnwM12buuKsoOyKZE',
    appId: '1:565444919181:ios:ab4d357217e672ea2487c4',
    messagingSenderId: '565444919181',
    projectId: 'dungeon-21925',
    storageBucket: 'dungeon-21925.firebasestorage.app',
    iosBundleId: 'com.example.dungeon2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3DWSoZURSDiUF-x5ASyXK4Axp1oE_V5k',
    appId: '1:565444919181:web:d29de95f31d26a8d2487c4',
    messagingSenderId: '565444919181',
    projectId: 'dungeon-21925',
    authDomain: 'dungeon-21925.firebaseapp.com',
    storageBucket: 'dungeon-21925.firebasestorage.app',
    measurementId: 'G-K3HBVWWN0V',
  );
}
